### PR TITLE
reorder summary, more important topics to top

### PR DESCRIPTION
**Pull request by straight-shoota**
This PR reorders some entries in the summary section `Syntax and Semantics`.

I think the navigation should list more relavant topics to make it easier accessible to readers. For example, `requiring files` was somewhere in the lower third`, yet it is essential for almost every Crystal program and certainly more used than `Attributes`.

I'd consider this an initial proposal and I'm open for feedback and other suggestions.
Of course, there is no single right ordering but we can certainly improve it a bit from what we have now.

see also #179

### CODE REVIEW

**Comment by bew** [comment]
(Taking an example) I think the `Union types` section was before `Control expressions` so that when it speaks about types being T or Nil (in the `Control expression` section), the user is not lost when reading the guides.

We need to decide if we want to help users to read it straight, or if we want them to jump from place to place in the lang reference.
In the end we'll probably have a proper `Tour of Crystal`, correctly ordered, but until then maybe we should try to keep the lang ref' easy to follow?

**Comment by straight-shoota** [comment]
I think the language reference should be logically structured, not necessarily in a sequential order like a tutorial.

Union types are conceptually a part of the section `Types & Methods`. It doesn't really make sense to discuss union types apart from everything else type-related. Besides, union types are already mentioned with the array and hash literals. It just doesn't work to introduce concepts consequetively while describing each in full detail because there are inevitably many cross-references.

**Comment by mverzilli** [comment]
@straight-shoota you mentioned this was an initial proposal. I think it's ok to be merged as is, but will wait for your confirmation to proceed.

**Comment by straight-shoota** [comment]
Yeah, this is GTG from my point.

**Pull request merged**
