### PR TITLE
Make Crystal's logo black again, add a white circle

### PR DESCRIPTION
**Pull request by oprypin**
**[Preview](https://pryp.in/p/4d90968d93ef4d8c7a3f1e44e59292f285940749/)**
[Before](https://crystal-lang.org/reference/)

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]
I suppose this is probably better than #458 for the css change?

**Comment by oprypin** [comment]
Yes, this is definitely better. Without the CSS the actual logo is way too small.

BTW I realized that I hadn't checked the mobile view. Well, now I did, and it's fine.

**Comment by bcardiff** [comment]
Thanks @oprypin

**Comment by j8r** [comment]
Hum... any reason why? I preferred it before, simpler. The GitHub icon does the same on this page, and on the .com site.

**Comment by oprypin** [comment]
@j8r I can understand, it's a branding issue

**Comment by oprypin** [comment]
The context is https://github.com/crystal-lang/crystal-book/pull/457#issuecomment-770864723

**Comment by j8r** [comment]
Ha ok I see, the light effect... I don't really mind at the end :sweat_smile: .
Remains to do the same for the forum :wink:

**Pull request merged**
