### PR TITLE
Dark Mode

### PR DESCRIPTION
**Pull request by timscodebase**
You docs sorely need a dark mode.  Here is a simple solution with batteries for new features

### CODE REVIEW

**Comment by timscodebase** [comment]
Dark mode

**Comment by straight-shoota** [comment]
Mkdocs-material already has dark mode implemented. I think we only need to enable it.

**Comment by Blacksmoke16** [comment]
Yea, should just need to be a configuration change. The related docs for it are: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode.

**Comment by straight-shoota** [comment]
Closing. We shouldn't run a custom implementation for dark mode and instead use the upstream feature configuration.

**Pull request closed without merging**
