### PR TITLE
Until: truthy -> falsey

### PR DESCRIPTION
**Pull request by n7olkachev**

### CODE REVIEW

**Comment by asterite** [comment]
Um, no. The body is executed until the condition becomes true. If it's true, then it's not executed anymore.

**Comment by RX14** [comment]
No, @asterite is correct, I clearly can't read :)

**Comment by mverzilli** [comment]
Same :P

**Comment by RX14** [comment]
Perhaps this indicates that the wording is confusing...

**Comment by asterite** [comment]
Perphaps `until` is confusing, just like `unless` is a bit confusing too :-)

**Comment by RX14** [comment]
They're not to me. Its just this documentation.

**Comment by n7olkachev** [comment]
Ahah, wording, yep:) 
Sorry for confusing, guys

**Pull request closed without merging**
