### PR TITLE
text: removed llvm latest version support note

### PR DESCRIPTION
**Pull request by waheedi**
text change for llvm version support

### CODE REVIEW

**Comment by waheedi** [comment]
whats up @deworrall92? Is improving the documentation a bad idea?

**Comment by RX14** [comment]
"when possible use the latest version" means "latest possible from the supported versions".

**Comment by waheedi** [comment]
Closing as per the community suggest :)

**Comment by RX14** [comment]
i suggest you change ythe text not remove it

**Comment by waheedi** [comment]
@RX14 Thanks for the suggestion Chris. I did update the text. I believe its more clear now.

**Comment by waheedi** [comment]
Thanks @RX14 @sdogruyol

**Pull request merged**
