### PR TITLE
Prepare repo for Multi-Languages

### PR DESCRIPTION
**Pull request by papilip**
Hello All,

This PR is to prepare this repository for Multi-Languages according the [gitbook documentation](https://toolchain.gitbook.com/languages.html)

@humboldtux have translate in [french](https://github.com/Crystal-French/fr.crystal-lang.org) and now, if you agree, i would like propose a PR with this translation.

### CODE REVIEW

**Comment by mverzilli** [comment]
Hi @papilip! Thanks for this! Currently translations are 100% community efforts, and it couldn't be other way since the core team can't ensure that Korean, Russian, Japanese and others are correct. Of course we have Julien, who could oversee the French translations, but I don't think he has the time and interest in taking that role.

So, while I think it is indeed neat to use gitbook's multilanguage features, I don't want us to become gatekeepers to each translation. Do you know of any way around this? Maybe there's a way for us to integrate this using git submodules?

**Comment by papilip** [comment]
Thank you @mverzilli for taking time to respond.

As much as I understand your concern not to host all the translations for a concern of reliability, as much as I think that you should propose a central space of accommodation of the translations.
Today there are translations that are scattered on the web.
Even an approximate translation makes it easier to get started.

If we look at how the book works on GIT https://github.com/progit
We can see that there is an organization for the book and there is a deposit of code for each translation, with the mention that these translations are the result of the efforts of the community.

I think it is your responsibility to allow a community to get together and give it the means to develop.
So a deposit for all the translations or a deposit by translation, it is up to you, if you wish ;-)
I have a translation into French that I am reading for myself, I will be happy to share it with the community.
In addition, I apologize for my English, it is French translated by GTranslate.

**Comment by mverzilli** [comment]
What we are doing with other languages is to let the community generate the translations, and when they feel they're ready, we point a subdomain to their content. For example, take a look at:

https://kr.crystal-lang.org/

So, I'd propose to follow these steps:

1. Publish the gitbook from: https://github.com/Crystal-French/fr.crystal-lang.org (you can see some instructions here: https://medium.com/@gpbl/how-to-use-gitbook-to-publish-docs-for-your-open-source-npm-packages-465dd8d5bfba).
1. Once the gitbook is published somewhere, let us know and we'll point `fr.crystal-lang.org` to it.

**Comment by papilip** [comment]
Thank you very much, I will follow your proposal and I will come back to you as soon as the translation will be ready.

**Pull request closed without merging**
