### PR TITLE
Rename 'installation/from_a_targz.md' => 'installation/from_tar-gz.md'

### PR DESCRIPTION
**Pull request by AtlasJan**
Removed article, as it refers to the format, rather than anything countable.

### CODE REVIEW

**Comment by r00ster91** [comment]
TravisCI fails because you need to rename the section in SUMMARY.md too.

**Comment by straight-shoota** [comment]
I doubt this little improvement is worth breaking all the links to the previous path.

**Comment by straight-shoota** [comment]
Grammatically, this can be seen as an ellipsis for "(Installation) from a targz (archive)". I don't think it really needs to be changed.

**Comment by AtlasJan** [comment]
oh ok. sorry.

**Comment by AtlasJan** [comment]
...feel free to close it, by the way.

**Pull request closed without merging**
