### PR TITLE
Fix list syntax for stricter Markdown parsers

### PR DESCRIPTION
**Pull request by oprypin**
This is needed to migrate to MkDocs but is also good on its own

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by bcardiff** [comment]
@oprypin with this change the on the fly summary is not nested as it should. I guess this is something on the mkdocs-literate-nav plugin since it was tailored for the previous summary.md , right?

I no longer see the database section grouping their articles with this change.

**Comment by oprypin** [comment]
@bcardiff Sorry, I don't understand what you mean. I don't see anything wrong in GitBook or MkDocs in the current state.

**Comment by oprypin** [comment]
Oh if you're on the branch of PR #433, then yes, it doesn't have this commit in it, so it's wrong there.

**Comment by bcardiff** [comment]
Oh, I see. thanks!

**Pull request merged**
