### PR TITLE
Disallow unchecked intra-site links

### PR DESCRIPTION
**Pull request by oprypin**
In CI, use regular expressions to check against the kinds of links that could be made safer by letting MkDocs check their validity:

* Links not ending with '.md' (but the check is specifically for '.html' and '/' endings)
* Links starting with '/' or containing the site URL itself.

Closes #498

### CODE REVIEW

**Comment by bcardiff** [comment]
Should this be a bin/ci script that can be run locally directly also?

**Comment by straight-shoota** [comment]
Makefile recipe?

**Comment by oprypin** [comment]
Ideally this would be a MkDocs plugin :D
Actually this, along with my previous ideas (namely, making links starting with `/` work correctly), is finally enough to justify a plugin

But yeah this is wishful thinking.

Back to reality, ... I don't know where to put this and make it look nicely.

@straight-shoota if you know how to put this conditional into makefile nicely, do you want to send a PR to my PR :smile:

**Comment by oprypin** [comment]
Ah by the way, `grep -P` is not normally available on Mac, so that's a significant downside of forcibly running this

**Review by straight-shoota — APPROVED** [review]

**Review by bcardiff — APPROVED** [review]
Next step should be to check for valid relative links as it's done in the website, right? Or is mkdocs already preventing bad internal links?

**Comment by oprypin** [comment]
Well that's the point - MkDocs checks internal links, so we prevent situations where it doesn't check them

**Comment by straight-shoota** [comment]
The website actually only checks for external links. https://github.com/crystal-lang/crystal-website/blob/af07adfccb686e5890b2dd6f687458d55eede2a6/Makefile#L26
But we could add that here, too. It just adds a dependency on a Ruby tool, which was trivial to sneek in the Gemfile for crystal-website :D

**Pull request merged**
