### PR TITLE
Document the process of creating static builds

### PR DESCRIPTION
**Pull request by rzane**
I'm definitely not an expert in this sort of thing, so it is likely that I'm using the wrong terminology.

I didn't find a concise guide to creating static binaries anywhere, but I have seen a lot of people asking about how to create them.

The idea of creating pre-compiled binaries was the main motivation for me to use crystal in the first place. I assumed it was possible, but I was extremely frustrated when I couldn't find an explanation of how to create precompiled binaries for macs.

### CODE REVIEW

**Comment by RX14** [comment]
Dynamically linked libraries are precompiled. I'm a bit reluctant to document static linking because it's really hard to do and hacky - and crystal doesn't *really* support it apart from on alpine linux.

**Comment by j8r** [comment]
Maybe we can only document _the Docker Way_ to build statically-linked libraries. Is there an official container for?

Note that for now some libraries miss static archives required for static linking in Alpline, like `zlib-dev`. We have to compile them ourselves.

**Comment by rzane** [comment]
Based on the numerous github issues that I read to get to this point, it definitely seems like a lot of people are interested in doing this sort of thing.

Perhaps this guide should explain the procedure, document the risks, and explain why it is not officially supported at this time.

So far, this is the only documentation that I've found on static linking:
* https://crystal-lang.org/docs/using_the_compiler/#creating-a-standalone-executable
* https://github.com/crystal-lang/crystal/wiki/Static-Linking

**Comment by mverzilli** [comment]
How about we add this to an "experimental" section below "Guides"? That way we can centralize advice while clearly signaling that it is currently a "use at your own risk" feature.

**Comment by straight-shoota** [comment]
I agree this should be added as a guide. It's already written that way.

But I don't think it should be labeled "experimental". Static linking works and is even an integral part of the compiler's own build process. I don't think there is anything experimental about it.
It just doesn't work on all systems. But that's not our fault.

**Comment by kalinon** [comment]
If we dont need this as experimental, should be good to merge then right?

**Comment by straight-shoota** [comment]
This was overtaken by #469
Nevertheless, thanks @rzane

**Pull request closed without merging**
