### PR TITLE
Add requirement to instructions

### PR DESCRIPTION
**Pull request by diasjorge**
Document that Crystal is required in order to build from source

### CODE REVIEW

**Comment by diasjorge** [comment]
I found this issue trying to compile from source. Found the solution in a comment for this issue: crystal-lang/crystal#1331

**Comment by asterite** [comment]
First paragraph in the document says:

> If you want to contribute then you might want to install Crystal from sources. But Crystal is written in Crystal itself! So you first need to use one of the previous described methods to have a running compiler.

**Comment by karlseguin** [comment]
Don't see too much harm in saying it twice. People might land on difference pages, or miss it once or not the other. Of course, that could be a slippery slope (why not say everything twice)...but it seems somewhere between benign and helpful in this case

**Comment by mverzilli** [comment]
Yeah, I guess most people jumps straight to the numbered list and follows the steps, so it doesn't harm to be explicit there. So let's be more explicit: @diasjorge, could you make the first step of the list be sth like: "Install the latest Crystal release. To compile Crystal, you need Crystal :)." 

Have the first sentence be a link that points to `/installation`. Then we can merge :).

**Comment by diasjorge** [comment]
I implemented the changes suggested per @mverzilli 
Although I think addressing the concerns mentioned I created another patch in #79 
In my case I jumped straight to the list and just skimmed over the first paragraphs. In the alternative patch I wrote everything as a list, hopefully you prefer the other patch and we can just close this one.

**Comment by mverzilli** [comment]
I like what you propose in #79, so let's move there.

**Pull request closed without merging**
