### PR TITLE
Move almost everything into a docs/ subdirectory

### PR DESCRIPTION
**Pull request by oprypin**
This is what MkDocs very strongly recommends.

Should not be merged before #433

Note the diff in the mkdocs config:
https://github.com/crystal-lang/crystal-book/commit/f2008082d40e95dde41dfdcbcfc4c727411258e9#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2

### CODE REVIEW

**Comment by oprypin** [comment]
How the repo looks: https://github.com/crystal-lang/crystal-book/tree/f2008082d40e95dde41dfdcbcfc4c727411258e9

**Review by straight-shoota — APPROVED** [review]

**Comment by bcardiff** [comment]
Before merging this the current CI should be disabled I guess, right? Otherwise the gitbook compilation will do unintended things.

I can turn-off travis if that is needed and we will be without CI until a github action is setup.

**Comment by oprypin** [comment]
I also adapted GitBook config here, and I tried locally that it still works. But we can also disable Travis, yes.

**Comment by bcardiff** [comment]
Let's disable travis first so nothing will get updated meanwhile

**Pull request merged**
